### ISSUE TITLE
Search update

### ISSUE THREAD

**Issue by enmust** [geocollections/geocase-ui#36]
**Fast search**

- Fast search and detail search should work together. 

- Fast search could be first object in detail search list.

**Detail search**

- Search field filters in select box should work + majority of them can be removed until the functionality is added

- Add filters similarly to some e-shops e.g., institution selection

- Add all fields search (not priority)

**Comment by ollehints** [comment]
- 'Detail search' could be 'Advanced search'
- In search fields fewer options should be included:
  - contains
  - equals 
  - starts with
  - does not contain
  - greater than
  - smaller than
- Search field should have search options in lowercase - 'contains' instead of 'Contains' 
- Main facets would be (API call a la: q=*&rows=0&facet=on&facet.mincount=1&facet.field=recordbasis&facet.field=highertaxon&facet.field=country&facet.field=datasetowner&facet.field=providername&facet.field=providername&facet.field=providercountry):
  - recordbasis
  - highertaxon
  - country
  - url (cannot be used for regular facet at the moment -- needs a boolean field in the index - can be added to DIH SQL as new fields 'has_image' or dynamic field in solr)
  - datasetowner
  - providercountry
  - providername
