### ISSUE TITLE
Detail page submission

### ISSUE THREAD

**Issue by enmust** [geocollections/geocase-ui#49]
![image](https://user-images.githubusercontent.com/14908993/87520190-48a8d780-c68b-11ea-819b-cac76df4f58e.png)

**Comment by enmust** [comment]
Probably should use some prototyping tool (https://www.figma.com/) to compare different ideas etc.

**Comment by ollehints** [comment]
Title section should be one col wide, not page width, as in many cases the right side would be empty (http://geocase.geocollections.info/specimen/196904). Then images and/or map would have more useful space in the top.
Title section should include:

- A small icon and specimen type. Instead of FossilSpecimen it should state Fossil etc, followed by Collection and Object ID (like 'GIT 388-1').
- The main title (h1) would be fullscientificname (without the 'Name: ' prefix).
- Then the other identifications (h2), but only if there are more than one name; NB! do not include the fullscientificname in the list of other identifications. If fossils, the name and other identifications should be in italics, otherwise not.

Changes in the main data section:
- label 'ID' should be 'GeoCASe ID'

Images section:
- Gallery view does not add much to the specimen view since there are not many images to show, and the regular view shows images in the same size (it would be very useful in search view).
- thumbnails would better fit to the right from the main image, that would be aligned left rather than centered. Then we might see the map too on full HD screen in case of more than one image.
- author and link section should be on the same panel as the main image, currently it is below.
