### ISSUE TITLE
Front page issues

### ISSUE THREAD

**Issue by ollehints** [geocollections/geocase-ui#70]
- Search help example links need to be updated.
- "Fast search" should be "Find quickly ..." and the placeholder text should be of same font size as the user input text
- Can we make search box active so that a user can start typing search string right away?
- Where to put short intro text about GeoCASe?

**Comment by enmust** [comment]
- Search help example links need to be updated.
- ~~"Fast search" should be "Find quickly ..." and the placeholder text should be of same font size as the user input text~~
- ~~Can we make search box active so that a user can start typing search string right away?~~

> Where to put short intro text about GeoCASe?

 https://github.com/geocollections/geocase-ui/blob/cfb587778a216fceb1720bcc3a6ac562b840c728/client/src/views/FrontPage.vue#L12-L19
